# coding: utf-8

"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from my_crs.openapi_client.api.ping_api import PingApi
from my_crs.openapi_client.api_client import ApiClient
from my_crs.openapi_client.configuration import Configuration


class TestPingApi(unittest.TestCase):
    """PingApi unit test stubs"""

    def setUp(self) -> None:
        configuration = Configuration(
            host="http://localhost:1323",
            username="11111111-1111-1111-1111-111111111111",
            password="secret",
        )
        api_client = ApiClient(
            configuration=configuration,
            header_name="ContentType",
            header_value="application/json",
        )
        self.api = PingApi(api_client=api_client)

    def tearDown(self) -> None:
        pass

    def test_v1_ping_get(self) -> None:
        """Test case for v1_ping_get

        Test authentication creds and network connectivity
        """
        self.api.v1_ping_get()


if __name__ == "__main__":
    unittest.main()
