# coding: utf-8

"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from my_crs.openapi_client.models.types_assessment_status import (
    TypesAssessmentStatus,
)


class TestTypesAssessmentStatus(unittest.TestCase):
    """TypesAssessmentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypesAssessmentStatus(self):
        """Test TypesAssessmentStatus"""
        # inst = TypesAssessmentStatus()


if __name__ == "__main__":
    unittest.main()
